//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public int ticket_ID { get; set; }
        public Nullable<int> event_ID { get; set; }
        public Nullable<int> customer_ID { get; set; }
        public int quantity { get; set; }
    
        public virtual circus_events circus_events { get; set; }
        public virtual customers customers { get; set; }
    }
}
